java.lang.ClassCastException: [Ljava.lang.String; cannot be cast to java.util.Collection (cherry picked from commit 8761cef80dc281d04c9cbdc44fd964eaf237b284)